### ISSUE TITLE
Fix code scanning alert - Reflected server-side cross-site scripting

### ISSUE THREAD

**Issue by xbdmHQ** [MugoSquero/LibreTotal#1]
Tracking issue for:
- [x] https://github.com/WhateverItWorks/LibreTotal-Reworked/security/code-scanning/1

**Comment by MugoSquero** [comment]
Since the value provided by the user is sent to virustotal and virustotal has its own XSS protections/sanitizations, it may be a false alarm because you can't insert HTML elements into the page. Also, the code does not display the user input directly, it sends a request to virustotal and displays the response, so the value is URL encoded no matter what. This means that you can't insert special characters like “<” or “>”.
